### ISSUE TITLE
Django admin: Allow admins to manage Federal Agencies via a table

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1032] opened 2023-09-15 20:57 UTC
### Issue Description

Currently, in the registrar, there's a drop down that lists the federal agencies. We should turn that into a table within Django admin so the list can be managed by analysts, as needed.

AC

- [ ] Model is added for Federal Agency, so that it contains agency type and name
- [ ] Model is updated for Domain Application so that it uses Federal agency table
- [ ] Update Tests

### Additional Context (optional)

Ensure that no other changes to models or the application, when these are changed.

### Issue Links

Relates to #1008

**Comment by abroddrick** [comment] 2023-09-21 18:19
Don't pick this one up as we are currently discussing using an external table or api end point that may have this publicly available already

**Comment by h-m-f-t** [comment] 2024-05-29 03:09
I think this might be OBE...? @PaulKuykendall

**Comment by h-m-f-t** [comment] 2024-06-03 13:56
This issue is a duplicate of #1896 and #2029 (and follow-on issues to those).

**Closed by h-m-f-t** 2024-06-03 13:56 UTC
Labels: dev, refinement
