### ISSUE TITLE
Add yes/no question about other employees to domain request form

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/manage.get.gov#661] opened 2023-05-31 16:33 UTC
We discussed adding a yes/no question asking domain requestors if they have other employees that could be contacted. [This text is in the Google doc version of the form](https://docs.google.com/document/d/1GTTeRvKfe3lA_w2U4X_CBk8Q7BpMe7W0m_eVZsTHzEE/edit#heading=h.sqyw64). 

(The current domain request form assumes the answer is yes.) This yes/no speed bump will hopefully clarify the purpose of these additional contacts.

Note that on the Organizational Contacts page the text "(optional)" was added to the subheading of "Organization contact." Once this ticket has been completed, the "(optional)" text needs to be removed.

AC: 

- [ ] Match this Figma [See the mockup for this page in Figma](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=392-6055&mode=design&t=qJf3zpvD9juOtXCA-0).
- [ ] Match yes/no question mentioned in the doc above.
- [ ] Change organizational contact fields to required as appropriate (making sure red asterisks are added to labels accordingly).
- [ ] Remove "(optional)" text from "Organization contact" sub-heading
- [ ] "_Required fields are marked with an asterisk (*)._" sentence is shown when "Yes" option is selected, with placement following the Figma mockup.
- [ ] Add unit test as appropriate.

Story: #897

**Comment by PaulKuykendall** [comment] 2023-07-31 19:12
@PaulKuykendall - revisit with Cameron.

**Comment by Katherine-Osos** [comment] 2023-08-01 16:36
Per @h-m-f-t  note in this [slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1690385200886169), this story should not be prioritized for MVP. Therefore, I removed the MVP label.

**Comment by Katherine-Osos** [comment] 2023-11-28 15:44
Looks like there's a duplicate of this same ticket with more details: #897 We should review both and combine during refinement.

**Comment by vickyszuchin** [comment] 2024-01-02 15:44
Moved this ticket from sprint 35 to sprint 36 to continue the work. Awaiting new assignee.

**Closed** 2024-01-11 00:43 UTC
Labels: dev, MVP

**Comment by vickyszuchin** [comment] 2024-01-11 17:24
This ticket needed a sprint to complete. It is a "Large" rather than a "Medium."
