### ISSUE TITLE
`Senior Official` replaces `Authorizing Official` in get.gov

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2259] opened 2024-06-04 17:32 UTC
### Issue description

Because the term `Authorizing Official` or AO has special meaning in the Federal government, we must refer to the role in the registrar and public-facing website differently.

As a result of #2096, we have determined that the term `Senior Official`, with the abbreviation SO, will replace the use of `Authorizing Official` everywhere in the code and user-facing content.

### Acceptance criteria

- [ ] All instances of `Authorizing Official` are replaced with `Senior Official` in code and content.

### Additional context

Rather than Product finding all instances of this content, it is recommended that dev performs the appropriate search through the entire code-base, to identify each occurrence, replacing as appropriate. Also, any context around that change must be reviewed, so that it continues to make sense to all parties.

Normal design review. May take a little longer.

### Links to other issues

Based on:
- [x] #2096 
Related to:
- [x] #2258 
- [ ] #2259 (This ticket)

**Comment by therealslimhsiehdy** [comment] 2024-06-25 18:35
This is basically done (approved by design and dev), just can't merge it yet until I merge #2258 (which will be in review by tomorrow)

**Closed** 2024-07-02 13:56 UTC
Labels: dev
