### ISSUE TITLE
UX: Determine Proper Usage for "Your Contact Info"

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#954] opened 2023-08-30 12:58 UTC
On the Manage Domain detail page (/domain/NN), determine the proper use and operation for "Your Contact Information" data.

There is some confusion about what should be displayed here, [based on this Slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1692648019648539), raised by Zander, and elaborated by Neil.

This was implemented based on #520 in Sprint 21.

Acceptance criteria:

- [ ] Design resolution for the proper operation of this field.
- [ ] Any tickets to remediate are created and refined.

**Comment by vickyszuchin** [comment] 2024-02-29 22:13
Duplicate of #1808

**Closed** 2024-02-29 22:13 UTC
Labels: design, refinement
