### ISSUE TITLE
Handle domain invitations when there are multiple users with the same email address

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#1546] opened 2023-12-20 14:47 UTC
### Current Behavior

When there are multiple users who have the same email address, when there is a domain invitation for that email address and one of those users logs in, the login fails.

### Expected Behavior

The user should be able to log in, no matter what the situation is with domain invitations. It's not obvious what we should do with a domain invitation that is trying to be retrieved when there are two users who could reasonably be retrieving it.

### Steps to Reproduce

1. You need two Login.gov users with different UUIDs who have the same email address in our system
2. Create a domain invitation for that email address to some domain
3. Try to log in as one of those users

### Additional Context

The underlying error comes from https://github.com/cisagov/manage.get.gov/blob/main/src/registrar/models/domain_invitation.py#L55 where the code tries to `get()` a `User` with a specific email address but doesn't handle the exception when there are more than one users that match the criteria. One possible solution is to add another `except MultipleObjectsReturned:` clause and handle that situation appropriately.

Refer to [Slack thread ](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1703140562484399
)for discussion

**Comment by neilmb** [comment] 2023-12-20 14:49
The safest thing to do is to not retrieve the invitation for any user in this exceptional situation. Another possibility would be to retrieve the invitation for every one of the users who have that email address.

**Comment by neilmb** [comment] 2023-12-20 14:49
It's still not totally clear how it is possible and/or likely that more than one Login.gov account can have the same email address.

**Comment by vickyszuchin** [comment] 2023-12-21 13:21
This ticket was pulled into sprint 35 (on 12/20) to focus on investigation of issue and formulation of solution because this issue has high business impact. The expectation is that NOT that it will be fully implemented at the conclusion of sprint 35.

**Comment by PaulKuykendall** [comment] 2023-12-21 18:13
Questions for LOGIN.GOV

1. Why do we see several different UUID with same email address??
2. What do other users of login.gov do, when experiencing this? (a non-unique email address), when they use the email as a lookup key?
3. What is the best security practice recommendation to deal with this?
4.

**Comment by PaulKuykendall** [comment] 2023-12-21 18:52
If someone tries to ADD an email to their personal login.gov account, which has already been associated wiht another login.gov account, they will receive this message:

```
This email address is already associated with an account.
This email address is already associated with a Login.gov account, so we can’t add it to another account. You must first delete or remove it from the account it is associated with. To do this, follow the link below and sign in with this email address. If you are not trying to add this email address to an account, you can ignore this message. 
Go to Login.gov 

	
https://secure.login.gov/ 
```

**Comment by PaulKuykendall** [comment] 2023-12-21 23:26
@h-m-f-t @neilmb @kewlguy781 @amcelya  - I am not yet comfortable with tossing this to Login.gov just yet.

I understand that this is reportedly happening in production. However, I've been trying to reproduce the condition with no success. And after our meeting today, then re-reading the ticket, I am not happy with my understanding of it.

For a question for login.gov above, #1, I don't think that situation should be able to happen in the real world.

**Comment by PaulKuykendall** [comment] 2024-01-02 19:41
We have determined that this is a one-off that is not actually a bug. Closing as can't repro. (Discussed in today's sprint planning)

**Closed by PaulKuykendall** 2024-01-02 19:41 UTC
Labels: research, bug
