### ISSUE TITLE
Design: Analyst Domain management User Flow

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#807] opened 2023-07-19 00:33 UTC
### Story

As a CISA analyst OR Superuser 
I want a way to modify and view the information that registrants enter on the Domain management pages
so that I can use the contact information when someone at the domain needs to be reached or edit information based on requests. 

### Acceptance Criteria

- a workflow, or update the existing analyst workflow, to indicate the data that may be edited/ viewed by analysts after a domain is approved and even live
- in this workflow, determine what items should be restricted from editing post MVP.

### Additional Context

It is important to be able to see which contacts are associated with a given domain's management, especially when needing to reach out to them. In the current system, analysts can view all domain management data but can only edit some data. Some examples include organization info and security email can be changed but Authorizing official and nameservers cannot be.

In current Django: The name server info, security email, and possibly other EPP items are not stored in the database and, therefore, not shown to an analyst in the admin.

### Issue Links

- #806

**Comment by h-m-f-t** [comment] 2023-07-19 03:18
As hinted, it's possible that analysts _should_ be restricted from making _some_ changes, but at the program level we do need super-admin-level capabilities, including the ability to modify DNS for domains. 

(I do think analysts should have the ability to update the authorizing official.)

**Comment by vickyszuchin** [comment] 2024-03-12 14:30
Refinement tag added: PO accept this in the backlog but suggest ACs be reviewed by design team to make sure that scope is clear.

**Comment by Katherine-Osos** [comment] 2024-07-31 23:10
@h-m-f-t @abroddrick This ticket seems outdated. Thoughts on closing this one?

**Closed** 2024-08-01 16:14 UTC
Labels: design, story, refinement
